name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  build:

    permissions:
      contents: write
    
    runs-on: windows-latest

    env:
      Project_Path: AutoPowerTimeOut.csproj

    steps:

      # Checkout codes
      - name: Checkout
        uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ${{ env.Project_Path }}

      # Build the project
      - name: Build
        run: dotnet build ${{ env.Project_Path }} --configuration Release --no-restore

      # Get package version
      - name: Get Package Version
        run: |
         $version = [system.diagnostics.fileversioninfo]::getversioninfo("bin\Release\net9.0-windows10.0.19041.0\AutoPowerTimeOut.dll").fileversion
         echo "release_version=$version" | out-file -filepath $env:github_env -encoding utf-8 -append

      # Zip the output files
      - name: Zip files
        run: |
          $zipName = "AutoPowerTimeOut-v${{ env.release_version }}.zip"
          Compress-Archive -Path "bin\Release\net9.0-windows10.0.19041.0\*" -DestinationPath $zipName

      # Publish to GitHub releases
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: AutoPowerTimeOut*.zip
          tag_name: "v${{ env.release_version }}"
